baseURL = 'https://orhanakkaya.de/'
languageCode = 'de-de'
title = 'WEBMINERS - eCommerce from Pott'
theme = "papermod"

#Tracking
googleAnalytics = 'G-DN2MGG0XBB'

[params.profileMode]
enabled = true
title = "WEBMINERS"
subtitle = "eCommerce from Pott"
#imageUrl = "https://baublog.orhanakkaya.de/images/ws.png"
imageTitle = "webminers"
imageWidth = 150
imageHeight = 150

#HeaderMenu
    [[menu.main]]
    identifier = "baublog"
    name = "baublog"
    url = "/baublog/"
    weight = 10

    [[menu.main]]
    identifier = "services"
    name = "services"
    url = "/services/"
    weight = 20

    [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects/"
    weight = 30

    [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 90

#Buttons
#    [[params.profileMode.buttons]]
#    name = "Posts"
#    url = "/posts"

#SocialMedia
    [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/orhanakkaya"

    [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/hanmeran"